[package]
name = "rlustenv_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
pyo3={version="0.18", features=["macros"]}

[features]
extension-module = ["pyo3/extension-module"]
